version: '3.3'
services:
  redis:
    image: "redis:alpine"
    restart: on-failure:3
  web:
    restart: on-failure:3
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - redis
  celery:
    restart: on-failure:3
    build: .
    command: celery -A tochka_test worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    restart: on-failure:3
    build: .
    command: celery -A tochka_test beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  nginx:
    restart: on-failure:3
    build: ./nginx
    ports:
     - 80:80
    depends_on:
      - web