# Generated by Django 3.0.4 on 2020-03-14 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('balance', models.IntegerField()),
                ('hold', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
